### ISSUE TITLE
OS Independent Paths

### ISSUE THREAD

**Issue by robb07** [NSasquatch/Wario-Land-3#31]
Using "\" in paths doesn't work on linux. Instead use os module to allow the game to work on both windows and linux.
e.g. 
    import os
    os.path.join("images","image.png")
- Components/SpearheadComponents.py
- Components/WarioComponents.py
- Graphics.py

**Comment by Nearoo** [comment]
Does it work on Linux now?

**Comment by robb07** [comment]
Yes it does. Thanks!

**Comment by Nearoo** [comment]
Great! Tell me what you think after trying it :grin:
